compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@medusajs/js-sdk@*":
    peerDependencies:
      awilix: ^8.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
